version: '3'

services:

  # main service
  api:
    build: .
    ports:
      - 8080:80
    volumes:
      - app-sync:/data

  # MYSQL database
  db:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  # simple database management GUI
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

# files mapping fix for MacOS
volumes:
  app-sync:
    external: true