version: '3'

services:

  # main service
  api:
    build: .
    ports:
      - 8088:80
    volumes:
      - ./html:/var/www/html

  # MYSQL database
  db:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
     image: adminer
     restart: always
     ports:
       - 8081:8080
