version: '3'

services:

  api:
    build: .
    ports:
      - 8080:80
    volumes:
      - app-sync:/data

  db:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  app-sync:
    external: true